
# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl: 'https://blog.kusuha.com/' # Include trailing slash
title: くすはさんのブログ
author: くすは
languageCode: ja-jp
contentDir: posts
publishDir: docs
copyright: Copyright © くすは; all rights reserved.
paginate: 10
theme: hermit
googleAnalytics: "G-36ZKMZ1PCV"

enableEmoji: true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# enableGitInfo: true

disqusShortname: ''

defaultContentLanguage: ja
hasCJKLanguage: true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      hardWraps: false
      unsafe: true # change to false to disable inclusion of rawHTML and math functions
      xhtml: false
    extensions:
      typographer: false
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: '--'
    lineNoStart: 1
    lineNos: true # always set to true # else line numbers won't show at all! even when you toggle them on in the UI
    lineNumbersInTable: false # toggling this on (i.e to true) or deleting this line will break the code blocks functionality. Will
    noClasses: false
    # style = "monokai"
    tabWidth: 2
params:
# Date format. Checkout https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for details.
  dateFormat: "2006/01/02 15:04"

# -- hermit theme config --
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum:  "2006/01/02"
  dateformNumTime: "2006/01/02 15:04"

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor: "#494f5c"

  homeSubtitle: ""
  footerCopyright: 'Copyright © くすは; all rights reserved.'
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl: "https://github.com/dj-kusuha/blog.github.io/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent: false  # Set "text-align: justify" to `.content`.

  relatedPosts: false  # Add a related content section to all single posts page

  code_copy_button: true # Turn on/off the code-copy-button for code-fields

  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  social:
  - name: "twitter"
    url: "https://twitter.com/dj_kusuha"

  - name: "github"
    url: "https://github.com/dj-kusuha"

menu:
  main:
  - name: "Home"
    url: ""
    weight: 10

  - name: "Posts"
    url: "posts/"
    weight: 20
