baseURL: "http://blog.kusuha.com/"
languageCode: "ja"
title: "くすはさんのブログ"
contentDir: "posts"
theme: "hugo-clarity"
params:
  author: "くすは"
  twitter: "@dj_kusuha"
#  introDescription: "エンジニアをやっています。趣味はバックギャモンとかお酒とか。"
  dateFormat: "2006/01/02"
  
