baseURL: "https://blog.kusuha.com/"
defaultContentLanguage: "ja"
languageCode: "ja-jp"
title: "くすはさんのブログ"
contentDir: "posts"
publishDir: "docs"
theme: 
- "hugo-clarity"
canonifyurls: true
params:
  author: "くすは"
  twitter: "@dj_kusuha"
#  introDescription: "エンジニアをやっています。趣味はバックギャモンとかお酒とか。"
  dateFormat: "2006/01/02"
  
