
[[main]]
  name = "Home"
  url = ""
  weight = -110

# social menu links

[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/dj_kusuha"
[[social]]
  name = "rss"
  weight = 3
  url = "index.xml"
